### ISSUE TITLE
Link saya 404 error

### ISSUE THREAD

**Issue by drishyatm** [wiremock/python-wiremock#30]
I saw the index.rst , the link to documentation is broken

* Documentation: https://github.com/platinummonkey/python-wiremock/overview

**Comment by platinummonkey** [comment]
fixed! Thanks!

**Comment by soonernotfaster** [comment]
This is still showing up on the site as "https://github.com/platinummonkey/python-wiremock/overview" on https://wiremock.readthedocs.io/en/latest/ although it is correct in the repo.

**Comment by platinummonkey** [comment]
oops, fixed in https://github.com/wiremock/python-wiremock/commit/7cee3459e9122d3dbe557863dfdf02b449a3536d
